### ISSUE TITLE
app/routes/gateway.py 문의

### ISSUE THREAD

**Issue by Coen90** [potenday-405/poten-gateway-python#1]
app/routes/gateway.py 에서 DB connection이 일어나고 있는데, 어떤 이유로 디비 커넥션이 일어나고 있는지 알 수 있을까요?!
JWT 토큰에 user_id는 들어있지 않을까 해서요!

**Comment by jihan-chillin** [comment]
회원 email 주소를 subject로 넣어서 JWT토큰 발행했는데 ( 추후 decode -> email 주소로 회원 조회 계획이였음 )
처음 발행했을 때, user_id값을 sub로 넣으면 되겠군요!

좋은 방향 제시해주셔서 감사합니다!
